HISSystem/Areas/Admin/Models/SMSViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GeneticSystem.Areas.Admin.Models
{
    public class SMSViewModel
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Body { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public bool IsActive { get; set; }
        public string FromMobile { get; set; }
        public string ToMobile { get; set; }  
        public string TriggerType { get; set; }
        public int TargetID { get; set; }

    }
}

HISSystem/Areas/Admin/Controllers/SMSController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Data.Helpers;
using Data.Models;
using GeneticSystem.Areas.Admin.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Service.UnitOfServices;

namespace GeneticSystem.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SMSController : Controller
    {
        public const int PageSize = 50;
        private readonly IHostingEnvironment _appEnvironment;
        private readonly IUnitOfService db;
        public SMSController(IUnitOfService db, IHostingEnvironment _appEnvironment)
        {
            this.db = db;
            this._appEnvironment = _appEnvironment;
        }
        public IActionResult Index()
        {
            var sms = new PagedData<SMS>();
            var smsList = db.SMSService.GetSMS().Where(x => x.IsActive == true).ToList();
            sms.Data = (smsList).Take(PageSize);
            sms.NumberOfPages = Convert.ToInt32(Math.Ceiling((double)smsList.Count() / PageSize));
            return View(sms);
           
        }
        public IActionResult Add()
        {
            return PartialView();
        }
        [HttpPost]
        public IActionResult Add(SMS model)
        {
            model.CreatedBy = Request.Cookies["ID"];
            model.IsActive = true;
            model.CreatedOn = DateTime.UtcNow;
            model.UpdatedOn = DateTime.UtcNow;
            var status = db.SMSService.Add(model);
            return RedirectToAction("index");


        }
        public IActionResult Update(int id)
        {
            var data = db.SMSService.GeById(id);
            return PartialView(data);
        }
        [HttpPost]
        public IActionResult Update(SMS model)
        {
            model.IsActive = true;
            model.CreatedOn = DateTime.UtcNow;
            model.UpdatedOn = DateTime.UtcNow;
            db.SMSService.Update(model);
            return RedirectToAction("index");
        }
        public IActionResult Delete(int id)
        {
            db.SMSService.Delete(id);
            return RedirectToAction("index");
        }
        public IActionResult GetSMS(int page, string searchstring)
        {
            var sms = new PagedData<SMS>();
            var smsList = db.SMSService.GetSMS().Where(x => x.IsActive == true).ToList();
            if (!string.IsNullOrEmpty(searchstring))
            {
                smsList = smsList.Where(x => x.Name != null && x.Name.Contains(searchstring.ToString(), StringComparison.OrdinalIgnoreCase) ||
                (x.Body != null && x.Body.Contains(searchstring, StringComparison.OrdinalIgnoreCase))).ToList();
            }
            sms.Data = (smsList).Skip(PageSize * (page - 1)).Take(PageSize);
            sms.NumberOfPages = Convert.ToInt32(Math.Ceiling((double)smsList.Count() / PageSize));

            return PartialView(sms);
        }
        public IActionResult Trigger()
        {
            var triggers = new PagedData<SMSTrigger>();

            var data = db.SMSService.GetAllSMSTriggers();
            triggers.Data = (data).Take(PageSize);
            triggers.NumberOfPages = Convert.ToInt32(Math.Ceiling((double)data.Count() / PageSize));

            return View(triggers);
        }
        public IActionResult AddTriggerSMS()
        {
            var model = new SMSTrigger();
            ViewBag.AllSMS = db.SMSService.GetSMS().Where(x => x.IsActive == true).ToList();
            return PartialView(model);
        }
        [HttpPost]
        public IActionResult AddTriggesSMS(SMSTrigger model)
        {
            model.IsActive = true;
            model.CreatedOn = DateTime.UtcNow;
            model.UpdatedOn = DateTime.UtcNow;
            var result = db.SMSService.AddTrigger(model);
            return RedirectToAction("Trigger");
        }
        public IActionResult UpdateSMSTrigger(int Id)
        {
            var model = db.SMSService.GetTriggersById(Id);
            ViewBag.AllSMS = db.SMSService.GetSMS().Where(x => x.IsActive == true).ToList();
            return PartialView(model);      
        }
        [HttpPost]
        public IActionResult UpdateSMSTriggers(SMSTrigger model)
        {
            model.IsActive = true;
            model.CreatedOn = DateTime.UtcNow;
            model.UpdatedOn = DateTime.UtcNow;
            db.SMSService.UpdateTrigger(model);
            return RedirectToAction("Trigger");

        }
        public IActionResult DeleteTrigger(int id)
        {
            db.SMSService.DeleteTrigger(id);
            return RedirectToAction("Trigger");
        }
        public IActionResult GetTrigger(int page, string searchstring)
        {
            var SMSTrigger = new PagedData<SMSTrigger>();
            var SMStriggerList = db.SMSService.GetAllSMSTriggers().Where(x => x.IsActive == true).ToList();
            if (!string.IsNullOrEmpty(searchstring))
            {
                SMStriggerList = SMStriggerList.Where(x => x.SMS != null && x.SMS.Name != null && x.SMS.Name.Contains(searchstring.ToString(), StringComparison.OrdinalIgnoreCase)).ToList();
            }
            SMSTrigger.Data = (SMStriggerList).Skip(PageSize * (page - 1)).Take(PageSize);
            SMSTrigger.NumberOfPages = Convert.ToInt32(Math.Ceiling((double)SMStriggerList.Count() / PageSize));

            return PartialView(SMSTrigger);

        }
        public IActionResult Send(SMSSendModel smsViewmodel)
        {
            var smsconfig1 = db.SMSService.GetSmsConfig();
            var smsapi = smsconfig1.ApiKey;
            try
            {
                var bodyFormat = " Dear User your detail are username: {0}, Password: {1}, From: {2} ";

                var body = smsViewmodel.Body;
                var body1 = smsViewmodel.Body1;
                var body2 = smsViewmodel.Body2;
                var smsBody = string.Format(bodyFormat,smsViewmodel.Body, smsViewmodel.Body1, smsViewmodel.Body2);
             
                //string strUrl = "http://smsservice.hadara.ps:4545/SMS.ashx/bulkservice/sessionvalue/sendmessage/?apikey="+smsapi+"&to="+smsViewmodel.ToMobile+"&msg="+smsViewmodel.Body;
                string strUrl = "http://smsservice.hadara.ps:4545/SMS.ashx/bulkservice/sessionvalue/sendmessage/?apikey="+smsapi+"&to="+smsViewmodel.ToMobile+"&msg="+ smsBody;

                // Create a request object  
                WebRequest request = HttpWebRequest.Create(strUrl);
                // Get the response back  
                HttpWebResponse response = (HttpWebResponse)request.GetResponse();
                Stream s = (Stream)response.GetResponseStream();
                StreamReader readStream = new StreamReader(s);
                string dataString = readStream.ReadToEnd();
                response.Close();
                s.Close();
                readStream.Close();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return Json(true);
        }

        public IActionResult CustSend(SMSSendModel smsViewmodel)
        {
            var smsconfig1 = db.SMSService.GetSmsConfig();
            var smsapi = smsconfig1.ApiKey;
            try
            {
                var bodyFormat = "Dear User: ";

                var body = smsViewmodel.Body;
                var body1 = smsViewmodel.Body1;
                var body2 = smsViewmodel.Body2;
                var smsBody = string.Format(bodyFormat, smsViewmodel.Body, smsViewmodel.Body1, smsViewmodel.Body2);

                //string strUrl = "http://smsservice.hadara.ps:4545/SMS.ashx/bulkservice/sessionvalue/sendmessage/?apikey="+smsapi+"&to="+smsViewmodel.ToMobile+"&msg="+smsViewmodel.Body;
                string strUrl = "http://smsservice.hadara.ps:4545/SMS.ashx/bulkservice/sessionvalue/sendmessage/?apikey=" + smsapi + "&to=" + smsViewmodel.ToMobile + "&msg=" + smsViewmodel.Body;

                // Create a request object  
                WebRequest request = HttpWebRequest.Create(strUrl);
                // Get the response back  
                HttpWebResponse response = (HttpWebResponse)request.GetResponse();
                Stream s = (Stream)response.GetResponseStream();
                StreamReader readStream = new StreamReader(s);
                string dataString = readStream.ReadToEnd();
                response.Close();
                s.Close();
                readStream.Close();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return Json(true);
        }
        public IActionResult SMSGroups()
        {
            var sms = new PagedData<SMSGroup>();
            ViewBag.ClientList = db.UserService.GetPatients().OrderByDescending(x => x.AddedDate).ToList();
            var smsgroupList = db.SMSService.GetSMSGroups().Where(x => x.IsActive == true).ToList();
            sms.Data = (smsgroupList).Take(PageSize);
            sms.NumberOfPages = Convert.ToInt32(Math.Ceiling((double)smsgroupList.Count() / PageSize));
            return View(sms);
        }
        public IActionResult AddSMSGroup()
        {
            ViewBag.ClientList = db.UserService.GetPatients().OrderByDescending(x => x.AddedDate).ToList();
            return View();
        }
        [HttpPost]
        public IActionResult AddSmsGroups(AddGroupViewModel model)
        {
            SMSGroup smsgroupmodel = new SMSGroup();
            smsgroupmodel.GroupName = model.GroupName;
            smsgroupmodel.IsActive = true;
            smsgroupmodel.CreatedOn = DateTime.UtcNow;
            smsgroupmodel.UpdatedOn = DateTime.UtcNow;
            var addnewgroup = db.SMSService.AddSMSGroup(smsgroupmodel);
            var addnewgroupid = addnewgroup.ID;
            foreach (var item in model.GroupClientLists)
            {
                item.GroupID = addnewgroupid;

HISSystem/Areas/Admin/Views/SMS/Add.cshtml
@model Data.Models.SMS

<div class="modal-dialog modal-lg">
    <!-- Modal content-->
    @using (Html.BeginForm("Add", "SMS", FormMethod.Post, new { enctype = "multipart/form-data", id = "createForm" }))
    {
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <center><h4 class="modal-title">New Template</h4></center>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-6">
                            <h4>Name</h4>
                            <div class="form-group">
                                @Html.TextBoxFor(model => model.Name, new { @class = "form-control", placeholder = "Name. . . " })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                    </div>
                    <div class="col-md-12">
                        <h4>Body</h4>
                        <div class="form-group">
                            @Html.TextAreaFor(model => model.Body, new { @class = "form-control", @rows = "20" })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn btn-outline-inverse">Cancel</button>
                <button type="submit" class="btn btn-success popup-savebtn">Save</button>
            </div>
        </div>
    </div>
    }
</div>
    

<link href="@Url.Content("https://fonts.googleapis.com/css?family=Open+Sans")" rel='stylesheet' type='text/css'>
<script src="@Url.Content("~/assets/Themes/ckeditor/ckeditor.js")" type="text/javascript"></script>
<script>
	//CKEDITOR.replace("Body");
</script>

HISSystem/Areas/Admin/Views/SMS/AddTriggerSMS.cshtml
@model Data.Models.SMSTrigger
@using Data.Helpers

<div class="modal-dialog modal-md">
    <!-- Modal content-->
    @using (Html.BeginForm("AddTriggesSMS", "SMS", FormMethod.Post, new { enctype = "multipart/form-data", id = "createForm" }))
    {
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <center>
                    <h4 class="modal-title">
                        Trigger SMS
                    </h4>
                </center>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <h4>Trigger Name</h4>
                        @Html.HiddenFor(model => model.ID)
                        <div class="form-group">
                            @Html.DropDownList("TriggerName", Html.GetEnumSelectList<SMSTriggerType>(), "Trigger to", new { @class = "form-control  chosen-select" })
                            @Html.ValidationMessageFor(model => model.TriggerName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-6">
                        <h4>Template</h4>
                        <div class="form-group">
                            @Html.DropDownListFor(model => model.SMSID, new SelectList(ViewBag.AllSMS, "ID", "Name"), "Select Template", new { @class = "form-control chosen-select" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn btn-outline-inverse">Cancel</button>
                <button type="submit" class="btn btn-warning popup-savebtn">Save</button>
            </div>
        </div>
    }
</div>


@*<script>
        var config = {
            '.chosen-select': {},
            '.chosen-select-deselect': { allow_single_deselect: true },
            '.chosen-select-no-results': { no_results_text: 'Oops, nothing found!' },
            '.chosen-placeholder_text-single': { placeholder_text_single: 'Select option' },
            '.chosen-select-width': { width: "100%" }
        }
        for (var selector in config) {
            $(selector).chosen(config[selector]);
        }
    </script>*@

<style>
    .chosen-container {
        width: 100% !important;
    }
</style>

HISSystem/Areas/Admin/Views/SMS/GetSMS.cshtml
@model Data.Helpers.PagedData<Data.Models.SMS>
<div class="table-responsive">
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th>Name</th>
                <th>Body</th>
                <th style="width:100px">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Data)
            {
                <tr>
                    <td>@item.Name</td>
                     <td>@item.Body</td>
                    <td>

                        <a href="#"><i class="fa fa-pencil fa-md base-dark" onclick="editSMS('@item.ID')" aria-hidden="true"></i></a>

                        <a href="#" class="mrgn-l-sm"><i class="fa fa-trash fa-md base-dark" onclick="DeleteSMS('@item.ID')" aria-hidden="true"></i></a>
                    </td>

                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4">
                    @for (int i = 1; i <= Model.NumberOfPages; i++)
                    {
                        <a class="page-number" onclick="getsmssearch(@i)" href="javascript:void();">@i</a>
                    }
                </td>
            </tr>
        </tfoot>

    </table>
</div>

HISSystem/Areas/Admin/Views/SMS/SMSGroupSend.cshtml
@model GeneticSystem.Areas.Admin.Models.SendSMSGroupModel
@using Data.Models
@{
    ViewData["Title"] = "Send SMS";
    Layout = "~/Views/Shared/_Admin.cshtml";
}
<style>
    .border-left {
        border-left: 1px solid black;
    }

    .mg-t {
        margin-top: 10PX;
    }
</style>

@using (Html.BeginForm("SendSMSToGroup", "SMS", FormMethod.Post))
{
    <div class="prtm-content">
        <div class="prtm-page-bar">
            <ul class="breadcrumb">
                <li class="breadcrumb-item text-capitalize"><h2>@ViewData["Title"]</h2></li>
                <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="#">Ui elements</a></li>
                <li class="breadcrumb-item"><a href="#" class="active"> Send To Group</a></li>
            </ul>
        </div>
        <div class="col-md-4 col-lg-4">
            <input type="submit" name="submit" value="Send" class="btn btn-xs btn-danger" />
            <a href="/admin/sms/smsgroups" class="btn btn-xs btn-info">Back</a>
        </div>
        <div class="form-style">
            <div class="row">
                <div class="col-md-12 col-lg-12">
                    <div class="prtm-block pos-relative">
                        <div class="row">
                            <div class="col-md-12 col-lg-12">
                                <div class="row">
                                   
                                    <div class="col-md-3 col-lg-5">
                                        <div class="form-group">
                                            <label for="Department">Group</label>
                                            @Html.DropDownListFor(m => m.GroupID, new SelectList(ViewBag.Groups, "ID", "GroupName"), "Select Group", new { @class = "form-control dropdown" })
                                        </div>
                                    </div>
                                    <div class="col-md-3 col-lg-5">
                                        <div class="form-group">
                                            <label for="Department">Client</label>
                                            @Html.DropDownListFor(m => m.UserID, new SelectList(ViewBag.Clients, "ID", "EnFirstName"), "Select Client", new { @class = "form-control dropdown" })
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-10">
                                        <div class="form-group">
                                            <label>Message</label>
                                            @Html.TextAreaFor(m => m.Message,5, 20, new { @Class = "form-control" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@section scripts{
    <script>
    $(document).ready(function () {
            var items = "<option value='0'>Select</option>";
            $('#FloorID').html(items);
            $('#RoomID').html(items);
        });
    $(document).ready(function () {
            $('#BuildingID').change(function () {
                var url = '@Url.Content("~/")' + "Admin/Bed/GetFloor";
                var ddlsource = "#BuildingID";
                console.log($(ddlsource).children("option:selected").val());
                $.getJSON(url, { BuildingID: $(ddlsource).children("option:selected").val() }, function (data) {
                    var items = '';
                    $('#FloorID').empty();
                    $.each(data, function (i, floor) {
                        items += "<option value='" + floor.value + "'>" + floor.text + "</option>";
                    });
                    $('#FloorID').html(items);
                })
            });
        });

        $(document).ready(function () {
            $('#FloorID').change(function () {
                var url = '@Url.Content("~/")' + "Admin/Bed/GetRoom";
                var ddlsource = "#FloorID";
                console.log($(ddlsource).children("option:selected").val());
                debugger
                $.getJSON(url, { FloorID: $(ddlsource).children("option:selected").val() }, function (data) {
                    var items = '';
                    $('#RoomID').empty();
                    $.each(data, function (i, room) {
                        items += "<option value='" + room.value + "'>" + room.text + "</option>";
                    });
                    $('#RoomID').html(items);
                });
            });
        });
    </script>
}

HISSystem/Areas/Admin/Views/SMS/SmsConfig.cshtml
@model Data.Models.SMSConfig

@{
    ViewData["Title"] = "SMS Config";
    Layout = "~/Views/Shared/_Admin.cshtml";
}
<style>
    .border-left {
        border-left: 1px solid black;
    }

    .mg-t {
        margin-top: 10PX;
    }

    .modal-backdrop {
        display: none !important;
    }

    .modal-open .modal {
        width: 300px;
        margin: 0 auto;
        background-color: transparent;
    }

    .mg-b {
        margin-bottom: 10PX;
    }

    .bed-box {
        border-radius: 7px;
        padding: 5px 10px;
        height: auto;
        text-align: center;
        float: left;
        margin-right: 3px;
        margin-bottom: 3px;
    }

        .bed-box img {
            width: 25px;
        }

    p.bed-title {
        font-size: 10px;
        font-weight: 600;
        color: #fff;
        margin: 0;
        margin-top: 5px;
    }
</style>
@*@using (Html.BeginForm("Add", "Patient", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {*@
@using (Html.BeginForm("AddApiKey", "SMS", FormMethod.Post))
{
    <div class="prtm-content">
        <div class="prtm-page-bar">
            <ul class="breadcrumb">
                <li class="breadcrumb-item text-capitalize"><h2>@ViewData["Title"]</h2></li>
                <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="#">Ui elements</a></li>
                <li class="breadcrumb-item"><a href="#" class="active"> SMS Config</a></li>
            </ul>
        </div>
        <div class="row mrgn-b-sm">
            <div class="col-md-12 col-lg-12">
                @if (Model.ID <= 0)
                {<input type="submit" name="submit" value="Save" class="btn btn-xs btn-primary" id="signupform" />}
                else
                {
                    <input type="submit" name="submit" value="Update" class="btn btn-xs btn-warning" />


                }

            </div>
        </div>

        <div class="row mg-b">
            <div class="col-md-12 col-lg-12">
                <div class="prtm-block pos-relative">
                    <div class="line-slide-tab">

                        <div class="tab-content pad-all-sm">
                            <div id="tab-26" class=" row tab-pane fade in active">
                                <div class="col-md-12 col-lg-12">
                                    <div class="row mrgn-b-sm">
                                        <div class="col-md-10 col-lg-10">
                                            
                                            <div class="form-group">
                                                <label>Api Key</label>
                                                @Html.TextBoxFor(x => x.ApiKey, new { @class = "form-control" ,onchange="GetBalance();" })
                                            </div>
                                           


                                            <div class="form-group">
                                                <label>Jawwal Balance</label>
                                               <input type="text" class="form-control" id="jawwal" name="jawwal" readonly />
                                            </div>
                                            <div class="form-group">
                                                <label for="Gender">Wataniya Balance </label>
                                                <input type="text" class="form-control" id="watania" name="watania" readonly />
                                            </div>
                                            <div class="form-group">
                                                <label for="Gender">International Balance</label>

                                                <input type="text" class="form-control" id="international" name="international" readonly />
                                            </div>
                                        </div>                          

                                    </div>

                                </div>

                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

}


<!-- Modal -->
<!---End Model--->
<!--filter bed Modal -->


@section Scripts{
<script>
    $(document).ready(function () {
        var api = $("#ApiKey").val();
        debugger
        if(api != "") {
            GetBalance();
                }
    });

    function GetBalance() {
        var api =$("#ApiKey").val();
         $.ajax({
        type: 'Get',
        url: "/admin/sms/GetApiBalance?ApiKey="+api,
        success: function (response) {
            console.log(response);
            $("#jawwal").val(response[0]);
            $("#watania").val(response[1]);
            $("#international").val(response[2]);
        }
    });


    }
   
    

</script>

}

HISSystem/Areas/Admin/Views/SMS/Update.cshtml
@model Data.Models.SMS

<div class="modal-dialog modal-lg">
    <!-- Modal content-->
    @using (Html.BeginForm("Update", "SMS", FormMethod.Post, new { enctype = "multipart/form-data", id = "createForm" }))
    {
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <center><h4 class="modal-title">New Template</h4></center>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-md-6">
                                @Html.HiddenFor(x => x.ID)
                                <h4>Name</h4>
                                <div class="form-group">
                                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control", placeholder = "Name. . . " })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            
                    </div>
                    <div class="col-md-12">
                        <h4>Body</h4>
                        <div class="form-group">
                            @Html.TextAreaFor(model => model.Body, new { @class = "form-control", @rows = "20" })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn btn-outline-inverse">Cancel</button>
                <button type="submit" class="btn btn-success popup-savebtn">Save</button>
            </div>
        </div>
            </div>
    }
</div>

<link href="@Url.Content("https://fonts.googleapis.com/css?family=Open+Sans")" rel='stylesheet' type='text/css'>
<script src="@Url.Content("~/assets/Themes/ckeditor/ckeditor.js")" type="text/javascript"></script>
<script>
	//CKEDITOR.replace("Body");
</script>

HISSystem/Areas/Admin/Views/SMS/UpdateSMSTrigger.cshtml
@model Data.Models.SMSTrigger
@using Data.Helpers

<div class="modal-dialog modal-md">
    <!-- Modal content-->
    @using (Html.BeginForm("UpdateSMSTriggers", "SMS", FormMethod.Post, new { enctype = "multipart/form-data", id = "createForm" }))
    {
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <center>
                    <h4 class="modal-title">
                        Trigger SMS
                    </h4>
                </center>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <h4>Trigger Name</h4>
                        @Html.HiddenFor(model => model.ID)
                        <div class="form-group">
                            @Html.DropDownList("TriggerName", Html.GetEnumSelectList<SMSTriggerType>(), "Trigger to", new { @class = "form-control  chosen-select" })
                            @Html.ValidationMessageFor(model => model.TriggerName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-6">
                        <h4>Template</h4>
                        <div class="form-group">
                            @Html.DropDownListFor(model => model.SMSID, new SelectList(ViewBag.AllSMS, "ID", "Name"), "Select Template", new { @class = "form-control chosen-select" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn btn-outline-inverse">Cancel</button>
                <button type="submit" class="btn btn-warning popup-savebtn">Update</button>
            </div>
        </div>
    }
</div>


@*<script>
        var config = {
            '.chosen-select': {},
            '.chosen-select-deselect': { allow_single_deselect: true },
            '.chosen-select-no-results': { no_results_text: 'Oops, nothing found!' },
            '.chosen-placeholder_text-single': { placeholder_text_single: 'Select option' },
            '.chosen-select-width': { width: "100%" }
        }
        for (var selector in config) {
            $(selector).chosen(config[selector]);
        }
    </script>*@

<style>
    .chosen-container {
        width: 100% !important;
    }
</style>