HISSystem/Areas/Admin/Controllers/LookupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Service.IServices;
using HISSystem.Areas.Admin.Models;
using Data.Helpers;
using Data.Models;
using Service.UnitOfServices;
using X.PagedList;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HISSystem.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class LookupController : Controller
    {
        public const int PageSize = 15;
        private readonly IUnitOfService db;
        public LookupController(IUnitOfService db)
        {
            this.db = db;
        }
        public IActionResult Index()
        {
            List<Lookup> lookupTry = new List<Lookup>();

            var lookupList = db.LookupService.GetLookups().Select(x => x.Type).Distinct();
            ViewBag.Lookups = lookupList;
            
            return View(lookupTry);
        }

        public IActionResult DevExpressDemo()
        {
            return View();
        }

        public IActionResult GetLookupIndex(string lookupName)
        {
            LookupIndexModel lookupIndex = new LookupIndexModel();
            lookupIndex.PagedLookups = new PagedData<Lookup>();
            lookupIndex.Lookup = new Lookup();
            ViewBag.LookupName = lookupName;

            var xray = db.LookupService.GetLookups().Where(x => x.IsActive == true).ToList();

            var result = xray.Where(x => x.Type.Equals(lookupName)).ToList();

            lookupIndex.PagedLookups.Data = result.OrderBy(x => x.ID).Take(PageSize).ToList();
            lookupIndex.PagedLookups.NumberOfPages = Convert.ToInt32(Math.Ceiling((double)result.Count() / PageSize));

            if (lookupName == "Floor")
            {
                foreach (var item in lookupIndex.PagedLookups.Data)
                {
                    item.Type = xray.Where(x => x.ID == Convert.ToInt32(item.ParentId)).FirstOrDefault().Name.ToString();
                }
            }
            else if (lookupName == "Room")
            {
                foreach (var item in lookupIndex.PagedLookups.Data)
                {
                    Lookup lookup = new Lookup();

                    lookup = xray.Where(x => x.ID == Convert.ToInt32(item.ParentId)).FirstOrDefault();

                    string grandParent = xray.Where(x => x.ID == Convert.ToInt32(lookup.ParentId)).FirstOrDefault().Name.ToString();

                    item.Type = grandParent + "/" + lookup.Name;
                }
            }

            return PartialView("_Index", lookupIndex);
        }
 
        [HttpGet]
        public IActionResult _GetLookupIndex(string lookupName, int page)
        {
            LookupIndexModel lookupIndex = new LookupIndexModel();
            lookupIndex.PagedLookups = new PagedData<Lookup>();
            lookupIndex.Lookup = new Lookup();
            ViewBag.LookupName = lookupName;

            var xray = db.LookupService.GetLookups().Where(x => x.IsActive == true).ToList();
            var result = xray.Where(x => x.Type.Equals(lookupName)).ToList();

            //var result = xray.Where(x => x.Type.Contains(lookupName)).ToList();

            lookupIndex.PagedLookups.Data = result.OrderBy(x => x.ID).Skip(PageSize * (page - 1)).Take(PageSize).ToList();
            lookupIndex.PagedLookups.NumberOfPages = Convert.ToInt32(Math.Ceiling((double)result.Count() / PageSize));

            

            if (lookupName == "Floor")
            {
                foreach (var item in lookupIndex.PagedLookups.Data)
                {
                    item.Type = xray.Where(x => x.ID == Convert.ToInt32(item.ParentId)).FirstOrDefault().Name.ToString();
                }
            }
            else if (lookupName == "Room")
            {
                foreach (var item in lookupIndex.PagedLookups.Data)
                {
                    Lookup lookup = new Lookup();

                    lookup = xray.Where(x => x.ID == Convert.ToInt32(item.ParentId)).FirstOrDefault();

                    string grandParent = xray.Where(x => x.ID == Convert.ToInt32(lookup.ParentId)).FirstOrDefault().Name.ToString();

                    item.Type = grandParent + "/" + lookup.Name;
                }
            }


            return PartialView("_Index", lookupIndex);
        }
  
        [HttpGet]
        public IActionResult Add(string lookupName)
        {
            switch (lookupName)
            {
                case "Floor":
                    ViewBag.Buildings = db.LookupService.GetLookUpByTypeName("Building");
                    break;

                case "Room":
                    ViewBag.Buildings = db.LookupService.GetLookUpByTypeName("Building");
                    ViewBag.Floors = db.LookupService.GetLookUpByTypeName("Floor");
                    break;
            }

            int result = db.LookupService.GetLookUpByTypeName(lookupName).Max(x => x.TypeID);
            Lookup lookup = new Lookup();
            lookup.TypeID = (++result);
            lookup.Type = lookupName;
            ViewBag.lookupName = lookupName;

            return PartialView("_Add", lookup);
        }

        [HttpGet]
        public IActionResult AddMaster()
        {
            Lookup lookup = new Lookup();
            lookup.TypeID = 1;
            lookup.Type = "";
            return PartialView("_AddMaster", lookup);
        }
        [HttpPost]
        public IActionResult AddNewMaster(Lookup lookup)
        {
            try { 
            lookup.AddedDate = DateTime.UtcNow;
            lookup.IsActive = true;
            var name = lookup.Name;
            var type = lookup.Type;
            lookup.Type = type.Trim();
            lookup.Name= name.Trim();
            db.LookupService.InsertUser(lookup);
            return Json(true);
            }
            catch(Exception ex)
            {
                throw ex;
            }
           
        }

        [Area("Admin")]
        public IActionResult GetFloor(string BuildingID)
        {
            List<Lookup> floorList = new List<Lookup>();
            List<Floor> Floors = new List<Floor>();
            floorList = db.LookupService.GetLookups().Where(x => x.ParentId == BuildingID).ToList();

            foreach (var item in floorList)
            {
                Floor floor = new Floor();
                floor.ID = item.ID;
                floor.Name = item.Name;
                Floors.Add(floor);
            }

            Floors.Insert(0, new Floor { ID = 0, Name = "Select" });

            return Json(new SelectList(Floors, "ID", "Name"));
        }

        [HttpPost]
        public IActionResult Add(Lookup lookup)
        {
            lookup.IsActive = true;
            var name = lookup.Name;
            lookup.Name = name.Trim();
            lookup.AddedDate = System.DateTime.Now;
            lookup.ModifiedDate = System.DateTime.Now;
            db.LookupService.InsertUser(lookup);

            return Json(true);

            //var lookupName = name;
            //LookupIndexModel lookupIndex = new LookupIndexModel();
            //lookupIndex.PagedLookups = new PagedData<Lookup>();
            //lookupIndex.Lookup = new Lookup();
            //ViewBag.LookupName = lookupName;

            //var xray = db.LookupService.GetLookups().Where(x => x.IsActive == true).ToList();

            //var result = xray.Where(x => x.Type.Equals(lookupName)).ToList();

            //lookupIndex.PagedLookups.Data = result.OrderBy(x => x.ID).Take(PageSize).ToList();
            //lookupIndex.PagedLookups.NumberOfPages = Convert.ToInt32(Math.Ceiling((double)result.Count() / PageSize));

            //if (lookupName == "Floor")
            //{
            //    foreach (var item in lookupIndex.PagedLookups.Data)
            //    {
            //        item.Type = xray.Where(x => x.ID == Convert.ToInt32(item.ParentId)).FirstOrDefault().Name.ToString();
            //    }
            //}
            //else if (lookupName == "Room")
            //{
            //    foreach (var item in lookupIndex.PagedLookups.Data)
            //    {
            //        Lookup lookups = new Lookup();

            //        lookups = xray.Where(x => x.ID == Convert.ToInt32(item.ParentId)).FirstOrDefault();

            //        string grandParent = xray.Where(x => x.ID == Convert.ToInt32(lookups.ParentId)).FirstOrDefault().Name.ToString();

            //        item.Type = grandParent + "/" + lookups.Name;
            //    }
            //}

            //return PartialView("_Index", lookupIndex);

        }

        public IActionResult Delete(int lookupID)
        {
            Lookup lookup = new Lookup();
            lookup = db.LookupService.GetLookup(lookupID);
            lookup.IsActive = false;
            db.LookupService.UpdateUser(lookup);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult GetLookup(int lookupID)
        {
            Lookup lookup = new Lookup();
            lookup = db.LookupService.GetLookup(lookupID);

            return PartialView("_GetLookup", lookup);
        }

        [HttpPost]
        public IActionResult GetLookup(Lookup lookup)
        {
            lookup.ModifiedDate = System.DateTime.Now;
            lookup.IsActive = true;
            db.LookupService.UpdateUser(lookup);

            return Json(true);
        }

        [HttpGet]
        public IActionResult SearchMasterLookup(string searchQuery)
        {
            List<Lookup> lookupTry = new List<Lookup>();

            if (searchQuery != null)
            {
                var lookupList = db.LookupService.GetLookupList().Where(x => x.Type.StartsWith(searchQuery, StringComparison.OrdinalIgnoreCase) && x.IsActive==true).Select(x => x.Type).Distinct().ToList();
                ViewBag.Lookups = lookupList;
            }
            else
            {

HISSystem/Areas/Admin/Views/Lookup/DevExpressDemo.cshtml
@{
    ViewData["Title"] = "DevExpressDemo";
    Layout = "~/Views/Shared/_Admin.cshtml";

}
@using DevExtreme.AspNet.Mvc;


@(Html.DevExtreme().DataGrid<Data.Models.User>()
    .DataSource(ds => ds.Mvc()
        .Controller("User")
        .LoadAction("ReturnUser")
        .InsertAction("Post")
        .Key("ID")
    )
    .RemoteOperations(true)
    .Columns(columns => {

        columns.AddFor(m => m.EnFirstName);
    })
    .Editing(e => e
        .AllowAdding(true)
    )
)

HISSystem/Areas/Admin/Views/Lookup/Search.cshtml
@model List<Data.Models.Lookup>
@*@foreach (var item in Model.Select((value, i) => new { i, value }))
    {<div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-info="@item.value.Type" data-parent="#bs-collapse" href="#one_@item.i">
                    @item.value.Type
                </a>
            </h4>
        </div>
        <div id="one_@item.i" class="panel-collapse collapse">
            <div class="row">
                <div class="col-md-5"> <a href="#" data-info="@item.value.Type" class="btn btn-xs btn-primary addLookup"><i class="fa fa-plus" aria-hidden="true"></i>Add</a></div>
                <div class="col-md-7 text-right search-block">
                    <div class="input-group pull-right" id="adv-search">
                        <input type="text" data-info="@item.value.Type" name="detailSearch" id="detailsearch" class="form-control detailsearch" placeholder="Search..." />
                    </div>
                </div>
            </div>
            <div class="panel-body-list" id="@item.value.Name">
            </div>
        </div>
    </div>
    }*@

@foreach (var item in ViewBag.Lookups)
{
    <h4><a href="#" class="list-group-item " onclick="GetLookupForm(this,'@item')">@item</a></h4>
}

HISSystem/Areas/Admin/Views/Lookup/_Add.cshtml
@model Data.Models.Lookup
@using Data.Models

<form @*action="/admin/lookup/add" method="post" id="addLookUp"*@ >
    <div class="prtm-content">
        <div class="row mrgn-b-sm">
            <div class="col-md-4 col-lg-4">
                <input type="button" name="submit" id="addNewLookUp" onclick="AddNewLookUp();" value="Save" class="btn btn-primary sbmtBtn" />
                <input type="button" id="closeModal" name="submit" value="Back" class="btn btn-warning" />
            </div>
            <div class="col-md-4 col-lg-4">
            </div>
            <div class="col-md-4 col-lg-4">
            </div>
        </div>
        <div class="form-style">
            <div class="row">
                <div class="col-md-12 col-lg-12">
                    <div class="prtm-block pos-relative">
                        <div class="row">
                            <div class="col-md-10 col-lg-10">
                                <div class="row mrgn-l-md">

                                    <div class="form-group">
                                        <label for="Type">Type</label>
                                        @Html.TextBoxFor(m => m.Type, null, new { @Class = "form-control", @readonly = true })
                                    </div>
                                    <div class="form-group">
                                        <label for="TypeID">TypeID</label>
                                        @Html.TextBoxFor(m => m.TypeID, null, new { @Class = "form-control", @readonly = true })
                                    </div>
                                    <div class="form-group">
                                        <label for="Name">Name</label>
                                        @Html.TextBoxFor(m => m.Name, null, new { @Class = "form-control", autocomplete = "off" })
                                    </div>
                                    @if (Model.Type == "Floor")
                                    {
                                        <div class="form-group">
                                            <label for="ParentId">Select Building</label>
                                            @Html.DropDownListFor(m => m.ParentId, new SelectList(ViewBag.Buildings, "ID", "Name"), "Select Building", new { @class = "form-control" })
                                        </div>
                                    }
                                    @if (Model.Type == "Room")
                                    {
                                        <div class="form-group">
                                            <label for="BuildingsList">Select Building</label>
                                            @Html.DropDownList("BuildingsList", new SelectList(ViewBag.Buildings, "ID", "Name"), "Select Building", new { @class = "form-control", onchange = "getFloors()" })
                                        </div>
                                    }
                                    @if (Model.Type == "Room")
                                    {
                                        <div class="form-group">
                                            <label for="ParentId">Select Floor</label>
                                            @Html.DropDownListFor(m => m.ParentId, new SelectList(ViewBag.Floors, "ID", "Name"), "Select Floor", new { @class = "form-control", disabled = "disabled" })
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

HISSystem/Areas/Admin/Views/Lookup/_AddMaster.cshtml
@model Data.Models.Lookup
@using Data.Models

<form action="/admin/lookup/addmaster" method="post" id="addMasterLookUp">
    <div class="prtm-content">
        <div class="row mrgn-b-sm">
            <div class="col-md-4 col-lg-4">
                <input type="button" name="submit" id="SaveLookup" onclick="SaveMasterLookup();" value="Save" class="btn btn-primary sbmtBtn" />
                <input type="button" id="closeModal" name="submit" value="Back" class="btn btn-warning" />
            </div>
            <div class="col-md-4 col-lg-4">
            </div>
            <div class="col-md-4 col-lg-4">
            </div>
        </div>
        <div class="form-style">
            <div class="row">
                <div class="col-md-12 col-lg-12">
                    <div class="prtm-block pos-relative">
                        <div class="row">
                            <div class="col-md-8 col-lg-8">
                                <div class="row mrgn-l-md">
                                    <div class="form-group">
                                        <label for="Type">Type</label>
                                        @Html.TextBoxFor(m => m.Type, null, new { @Class = "form-control", autocomplete = "off", required = "required"  })
                                    </div>
                                    <div class="form-group">
                                        <label for="TypeID">TypeID</label>
                                        @Html.TextBoxFor(m => m.TypeID, null, new { @Class = "form-control", @readonly = true })
                                    </div>
                                    <div class="form-group">
                                        <label for="Name">Name</label>
                                        @Html.TextBoxFor(m => m.Name, null, new { @Class = "form-control", autocomplete = "off", required = "required" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

HISSystem/Areas/Admin/Views/Lookup/_GetLookup.cshtml
@model Data.Models.Lookup
@using Data.Models

<form @*action="/admin/lookup/GetLookup" method="post" id="editLookUp"*@ >
    <div class="prtm-content">
        <div class="row mrgn-b-sm">
            <div class="col-md-4 col-lg-4">
                <input type="button" name="submit" onclick="EditLookUp();" value="Update" class="btn btn-warning sbmtBtn" />
                <input type="button" name="submit" value="Back" class="btn btn-info" />
            </div>
            <div class="col-md-4 col-lg-4">
            </div>
            <div class="col-md-4 col-lg-4">
            </div>
        </div>
        <div class="form-style">
            <div class="row">
                <div class="col-md-12 col-lg-12">
                    <div class="prtm-block pos-relative">
                        <div class="row">
                            <div class="col-md-8 col-lg-8">
                                <div class="row mrgn-l-md">
                                    @Html.HiddenFor(m => m.ID)
                                    <div class="form-group">
                                        <label for="Type">Type</label>
                                        @Html.TextBoxFor(m => m.Type, null, new { @Class = "form-control", @readonly = true })
                                    </div>
                                    <div class="form-group">
                                        <label for="TypeID">TypeID</label>
                                        @Html.TextBoxFor(m => m.TypeID, null, new { @Class = "form-control", @readonly = true })
                                    </div>
                                    <div class="form-group">
                                        <label for="Name">Name</label>
                                        @Html.TextBoxFor(m => m.Name, null, new { @Class = "form-control", autocomplete = "off" })
                                    </div>
                                    <div class="form-group">
                                        <label for="IsActive">Is Active</label>
                                        @Html.CheckBoxFor(m => m.IsActive, new { @checked = "checked", style = "right:0px !important" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

HISSystem/Areas/Admin/Views/Lookup/_Index.cshtml
@model HISSystem.Areas.Admin.Models.LookupIndexModel
    <div class="prtm-content">
            <div class="row">
                <div class="col-md-7 text-left search-block">
                    <div class="input-group pull-right" id="adv-search">
                        <input type="text" data-info="@ViewBag.LookupName" name="detailSearch" id="detailsearch" class="form-control detailsearch" placeholder="Search Lookup..." />
                    </div>
                </div>
                <div class="col-md-5 col-sm-5 col-xs-12">
                    <button type="button" class="btn btn-xs btn-outline-warning add-btn addLookup sbmtBtn" data-info="@ViewBag.LookupName">
                        <i class="fa fa-plus" aria-hidden="true"></i>
                        &nbsp;Add LookupType
                    </button>
                    <h3 id="lName"></h3>
                </div>
            </div>
        <div class="row mrgn-b-xs">
            <div class="prtm-block mrgn-b-md">
                <div class="row">
                    <div class="col-md-12 col-lg-12 col-xs-12">
                        <div class="prtm-full-block">
                            <div class="table-responsive">
                                <table id="lookupDetailList" class="table table-striped table-hover table-bordered">
                                    <thead>
                                        <tr>
                                            <th class="numeric">Lookup Type</th>
                                            <th class="numeric">Lookup Name</th>
                                            <th class="numeric">Lookup TypeID</th>
                                            <th class="numeric">IsActive?</th>
                                            <th class="numeric" colspan="2">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.PagedLookups.Data)
                                        {
                                            <tr>
                                                <td>@item.Type</td>
                                                <td>@item.Name</td>
                                                <td>@item.TypeID</td>
                                                <td>@item.IsActive</td>
                                                <td>@Html.ActionLink("", "Delete", "Lookup", new { lookupID = @item.ID }, new { @Class = "fa fa-trash mrgn-l-xs fa-2x" })</td>
                                                <td id="@item.ID" class="editLookup"><i style="cursor:pointer" class="fa fa-edit fa-2x"></i></td>
                                            </tr>
                                        }
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <td colspan="6" value="@ViewBag.LookupName" id="@ViewBag.LookupName">
                                                @for (int i = 1; i <= Model.PagedLookups.NumberOfPages; i++)
                                                {
                                                    <a class="page-number" href="javascript:void(0);">@i</a>
                                                }
                                            </td>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                </div>
            </div>
        </div>
    </div>

HISSystem/Areas/Admin/Views/Lookup/_SearchDetail.cshtml
<table id="lookupDetailList" class="table table-striped table-hover table-bordered">
    <thead>
        <tr>
            <th class="numeric">Lookup Type</th>
            <th class="numeric">Lookup Name</th>
            <th class="numeric">Lookup TypeID</th>
            <th class="numeric">IsActive?</th>
            <th class="numeric" colspan="2">Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.PagedLookups.Data)
        {
            <tr>
                <td>@item.Type</td>
                <td>@item.Name</td>
                <td>@item.TypeID</td>
                <td>@item.IsActive</td>
                <td>@Html.ActionLink("", "Delete", "Lookup", new { lookupID = @item.ID }, new { @Class = "fa fa-trash mrgn-l-xs fa-2x" })</td>
                <td id="@item.ID" class="editLookup"><i style="cursor:pointer" class="fa fa-edit fa-2x"></i></td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="6" value="@ViewBag.LookupName" id="@ViewBag.LookupName" ">
                @for (int i = 1; i <= Model.PagedLookups.NumberOfPages; i++)
                {
                    <a class="page-number" href="javascript:void()">@i</a>
                }
            </td>
        </tr>
    </tfoot>
</table>